// import { UserProvider } from './UserContext'
// import NavBar from './NavBar'
// import './globals.css'
// import { Inter } from 'next/font/google'
//
// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
//
// export default function RootLayout({
//                                        children,
//                                    }: {
//     children: React.ReactNode
// }) {
//     return (
//         <html lang="en">
//         <body className={inter.className}>
//         <UserProvider>
//             <NavBar />
//             {children}
//         </UserProvider>
//         </body>
//         </html>
//     )
// }


// Verison 1.2
// import { UserProvider } from './UserContext'
// import NavBar from './NavBar'
// import ConsoleLogger from './ConsoleLogger'
// import './globals.css'
// import { Inter } from 'next/font/google'
//
// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
//
// export default function RootLayout({
//                                        children,
//                                    }: {
//     children: React.ReactNode
// }) {
//     return (
//         <html lang="en">
//         <body className={inter.className}>
//         <UserProvider>
//             <div className="flex flex-col min-h-screen">
//                 <NavBar />
//                 <div className="flex flex-1">
//                     <main className="w-3/4 p-4 overflow-auto">
//                         {children}
//                     </main>
//                     <aside className="w-1/4 border-l border-gray-200 flex flex-col">
//                         <div className="h-[calc(100vh-64px)] overflow-hidden">
//                             <ConsoleLogger />
//                         </div>
//                     </aside>
//                 </div>
//             </div>
//         </UserProvider>
//         </body>
//         </html>
//     )
// }

// Verison 1.3

import { UserProvider } from './lib/UserContext'
import NavBar from './ui/NavBar'
import './ui/globals.css'
import { Inter } from 'next/font/google'
import RightSidebar from './lib/RightSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <UserProvider>
            <div className="flex flex-col min-h-screen">
                <NavBar />
                <div className="flex flex-1">
                    <main className="w-3/4 p-4 overflow-auto">
                        {children}
                    </main>
                    <RightSidebar />
                </div>
            </div>
        </UserProvider>
        </body>
        </html>
    )
}