import type {Metadata} from "next";
import "./globals.css";
import NavBar from "@/app/NavBar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <NavBar /> {/*Default to all pages*/}
        {children} {/*All the react child components i.e. our application specific components will be displayed here*/}
        </body>
        </html>
    );
}
